In [2]:
# Addition of matrix 
import numpy as np
import time

In [75]:
class array:
    def __init__(self, lst) -> None:
        self.lst = lst

    def reshape(self, m, n):
        M = []
        tmp = []
        for i in self.lst:
            tmp.append(i)
            if len(tmp) == n:
                M.append(tmp)
                tmp = []
        self.lst = M

    def __add__(self, other):
        r1 = len(self.lst)
        c1 = len(self.lst[0]) 
        r2 = len(other.lst)
        c2 = len(other.lst[0])
        if (r1, c1) == (r2, c2):
            M = eval(str([[0]*c1] * r1))
            for i in range(r1):
                for j in range(c1):
                    M[i][j] = self.lst[i][j] + other.lst[i][j]
            return M
        else:
            return 'Invalid Operation' 

In [76]:

arr1 = array([2, 5, 0, 0, 7, 1])
arr2 = array([2, 4, 6, 8, 1, 0])
arr1.reshape(2, 3)
arr2.reshape(2, 3)

out = arr1 + arr2

print(out)

[[4, 9, 6], [8, 8, 1]]


In [22]:
data = range(100000)
arr = np.array(data)
lst = list(data)

In [23]:
strt = time.time()
out = [i*2 for i in lst]
stop = time.time()
print('list time', stop-strt)


strt = time.time()
out = arr * 2
stop = time.time()
print('Array time', stop-strt)

list time 0.0020041465759277344
Array time 0.0008070468902587891


In [ ]:
# Question 1: check wheather list is flatten or nested 
# Question 2: Convert Given nested list into flatten list

'''
input:
[[2, 4], 10, [[[[10]]]], 0, [3]]

output:
[2, 4, 10, 10, 0, 3]
'''





In [5]:
import numpy as np

def custom_sum(arg1, arg2):
    if isinstance(arg1, np.ndarray) and isinstance(arg2, np.ndarray):
        print(arg1 + arg2)
    elif isinstance(arg1, list) and isinstance(arg2, list):
        print('Both arguments are lists, not arrays')
    else:
        print('')

# logic here 
        

<class 'numpy.ndarray'>


In [8]:
import numpy as np
mat = np.array([[1,2],[3,4],[5,6]]).astype(float)
arr = np.ravel(mat)
print(mat)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [20]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# orignal
print('\nOrignal') 
print(arr, id(arr))

# Using flatten()
flattened_copy = arr.flatten()
print('\nFlatten')
flattened_copy[1] = 200
print(flattened_copy, id(flattened_copy))

ravel_copy = np.ravel(arr)
print('\nRavel Copy')
ravel_copy[0] = 100
print(ravel_copy, id(ravel_copy)) 

print('\nOrignal') 
print(arr, id(arr))


Orignal
[[1 2 3]
 [4 5 6]] 4934718960

Flatten
[  1 200   3   4   5   6] 4911513008

Ravel Copy
[100   2   3   4   5   6] 4934718768

Orignal
[[100   2   3]
 [  4   5   6]] 4934718960
