In [1]:
# import numpy 
import numpy as np

In [10]:
lst1 = [12, 30, 12, 60]
arr1 = np.array(lst1)
print(arr1)

[12 30 12 60]


In [15]:
lst2 = [6, 2, 4, 18]
arr2 = np.array(lst2)
print(arr2)


[ 6  2  4 18]


In [16]:
arr1 + arr2

array([18, 32, 16, 78])

In [ ]:
# list (array )
# 1-D Array 
# 2-D Array 


In [5]:
# covert 1d array (list) to matrix (2-d array ) 
lst = [1, 3, 5, 6, 7, 2]
row, column = 2, 3

'''
input
2 3 4 5 6 1
2 3

output
2 3 4
5 6 7
'''

# output
'''
[[1, 3, 5],
 [6, 7, 2]]
'''

[1]

In [37]:
class designMatrix:
    def __init__(self,lst):
        self.lst=lst
        
    def validity(self,m,n):
        return len(self.lst) == m*n
    
    def create_matrix(self, m, n):
        count = 0
        matrix = []
        tmp = []
        for i in self.lst:
            tmp.append(i)
            count += 1
            if count == n:
                matrix.append(tmp)
                tmp = []
                count = 0
        self.matrix = matrix
    def disp_matrix(self):
        for i in self.matrix:
            print(*i)

# st = list(map(int,input().split()))  # 
lst = [2, 3, 4,  6, 7, 3]
# m, n = input().split() # 2 3
m, n = 2, 3

mat = designMatrix(lst)
if mat.validity(m, n):
    mat.create_matrix(m, n)
    mat.disp_matrix()
else:
    print('Invalid Dimensions')


2 3 4
6 7 3


In [35]:
x = [2, 4, 5]
print(*x)

2 4 5


In [ ]:
'''
3 2
23 4 34 5 2 5 7


False
'''