In [1]:
import numpy as np

# Creating a 2D array (3x3 matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Creating a 3D array (2x3x3)
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

print("2D Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)

print("\n3D Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Shape: (2, 3, 3)


In [11]:
import numpy as np
a = np.zeros((3, 4, 2, 2))
print(a) 

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
