In [1]:
# numpy 

import numpy as np

In [5]:
# array (): to convert the any seq into array 

# example 1 
lst = [2, 4, 6, 8, 9]
arr = np.array(lst)
print(arr, arr.ndim)

[2 4 6 8 9] 1


In [6]:
# example 2
lst = [[2, 4, 6], [0, 1, 3]]
arr = np.array(lst)
print(arr)
print(arr.shape)
print(arr.ndim)

[[2 4 6]
 [0 1 3]]
(2, 3)
2


In [18]:
arr1 = np.array([3, 2, 4, 6, 8, 0])
arr2 = np.array([1, 2, 4, 5, 5, 0])

# arr1.shape = (3, 2)
# arr1.shape = (3, 2)

m1 = arr1.reshape((2, 3))
m2 = arr2.reshape((2, 3))

m = np.subtract(m1, m2)

print(m)
# print(out)

[[2 0 0]
 [1 3 0]]


In [20]:
import numpy as np 

m, n = list(map(int, input().split()))
arr = np.eye(m, n)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
