#version

In [1]:
print(np.__version__)
1.18.1

# Create a NumPy ndarray Object
# The array object in NumPy is called ndarray.

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
[1 2 3 4 5]
<class 'numpy.ndarray'>

In [3]:
obj = (1, 2, 3, 4, 5)
print(type(obj))
print(obj)
arr = np.array(obj)
print(arr)
print(type(arr))
<class 'tuple'>
(1, 2, 3, 4, 5)
[1 2 3 4 5]
<class 'numpy.ndarray'>

In [4]:
obj = {"CA": 8, "CB": 10}
print(type(obj))

arr = np.array(obj)
print(arr)
print(type(arr))
<class 'dict'>
{'CA': 8, 'CB': 10}
<class 'numpy.ndarray'>

In [5]:
numlist = [  [ [5,6,7],[4,3,6,8] ] , [[5,6,7]], [[5,6,7],[4,3],[6,8]] ]
print(len(numlist))
print(len(numlist[0]))
print(len(numlist[1]))
print(len(numlist[2]))
print(len(numlist[2][1]))
3
2
1
3
2

In [6]:
arr = np.array(["Rohan", "Riya"])
print(arr)
print(type(arr))
print(arr.ndim)
============

In [7]:
arr = np.array(67)
print(arr)
print(type(arr))
print(arr.ndim)
['Rohan' 'Riya']
<class 'numpy.ndarray'>
1
============
67
<class 'numpy.ndarray'>
0

# Dimensions in Arrays
# A dimension in arrays is one level of array depth (nested arrays)

In [8]:
aarr = np.array(23)
print(aarr)
print("Dimension of aarr = ",aarr.ndim)
23
Dimension of aarr =  0

In [9]:
aaarr = np.array([1, 2, 3,4, 5, 6])

print(aaarr)
print("Dimension of aaarr = ",aaarr.ndim)
[1 2 3 4 5 6]
Dimension of aaarr =  1

In [10]:
barr = np.array([[1, 2, 3], [4, 5, 6]])

print(barr)
print("Dimension of barr = ",barr.ndim)
[[1 2 3]
 [4 5 6]]
Dimension of barr =  2

In [11]:
list = [1,2,"Rahul"]
print(list)
[1, 2, 'Rahul']

In [12]:
arr = np.array(456)
print(arr)
print(type(arr))
print(arr.ndim)
456
<class 'numpy.ndarray'>
0

In [13]:
carr = np.array([
               [ [1,2] ],
               [ [1,2,9] ] , 
               [ [1,2] ]
            ])

print(carr)
print("Dimension of carr = ",carr.ndim)
print(carr.shape)
[[[1 2]]
 [[1 2 9]]
 [[1 2]]]
Dimension of carr =  2
(3, 1)

In [14]:
var = (a*a for a in range(8))
print(var)
numlist = list(var)
print(type(numlist))
print(numlist)
<generator object <genexpr> at 0x000001C90E4A6B48>
<class 'list'>
[0, 1, 4, 9, 16, 25, 36, 49]

In [15]:
carr1 = np.array([
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
            ])

print(carr1[0][1][2]) #1st 2-D, 2nd row, 3rd element
print(carr1[0,1,2])
print(carr1)
print("Dimension of carr1 = ",carr1.ndim)
print(carr1.shape)
6
6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of carr1 =  3
(3, 3, 3)

In [16]:
print(aarr.ndim)
print(barr.ndim)
print(carr.ndim)
0
2
3

In [17]:
narr = np.array([1, 2, 3, 4], ndmin=5)

print(narr)
print('number of dimensions :', narr.ndim)

print(narr[0]) # 4-d
print(narr[0,0]) # 3-d
print(narr[0,0,0]) # 2-d
print(narr[0,0,0,0]) # 1-d
print(narr[0,0,0,0,1]) #2nd element from above 1-d array
[[[[[1 2 3 4]]]]]
number of dimensions : 5

[[[[1 2 3 4]]]]
[[[1 2 3 4]]]
[[1 2 3 4]]
[1 2 3 4]
[2 3 4]

# Higher Dimensional Arrays

In [18]:
narr = np.array([1, 2, 3, 4], ndmin=5)
print(narr)
print(narr[0])
print('number of dimensions :', narr.ndim)
print(narr[0,0,0])

# NumPy Array Indexing
# Access Array Elements

In [19]:
print(barr, end = "\n\n")
print(barr[0])

# Access 2-D Arrays

In [20]:
print(barr[0, 1])
print(barr[1, 2])

# Access 3-D Arrays

In [21]:
print(carr1[0, 1, 2])

# Negative Indexing

In [22]:
print('Last element from 2nd dim: ', barr[1, -1])

# Slicing arrays

In [23]:
print(barr, end = "\n\n")
print(barr[0, 1:3])

# Data Types in NumPy

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

In [25]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

In [26]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

In [27]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

# Converting Data Type on Existing Arrays

In [28]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

# NumPy Array Copy vs View

In [29]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

# Check if Array Owns its Data

In [31]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

# Array Shape

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

# Reshaping arrays

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(newarr)

# Iterate Arrays

In [34]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

# Iterating 2-D Arrays

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

# Searching Arrays

In [37]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# Sorting Arrays

In [38]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# Filtering Arrays

In [39]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# Random Numbers in NumPy

In [40]:
from numpy import random

x = random.randint(100)

print(x)

In [41]:
x = random.rand()

print(x)

# Generate Random Array

In [42]:
x = random.randint(100, size=(5))

print(x)

In [43]:
x = random.randint(100, size=(3, 5))

print(x)

# Generate Random Float

In [44]:
x = random.rand(5)

print(x)

In [45]:
x = random.rand(3, 5)

print(x)

# Random Choice

In [46]:
x = random.choice([3, 5, 7, 9])

print(x)

In [47]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

# Create a Random Array

In [48]:
x = random.randint(100, size=(3, 5))

print(x)

# NumPy Array Join

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

In [50]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

In [51]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

# NumPy Array Splitting

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

In [58]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

# NumPy Array Searching

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr == 4)

print(x)

In [63]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2 == 0)

print(x)

In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

In [65]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

In [66]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

In [67]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# NumPy Array Sorting

In [68]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

In [69]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

In [70]:
arr = np.array([True, False, True])

print(np.sort(arr))

# NumPy Array Filtering

In [71]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

In [72]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [74]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filter_arr = arr > 5

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)