In [1]:
import numpy
print(numpy.__version__)

1.18.1

In [2]:
list = [1,2,3,4,5,6]
print(type(list))

<class 'list'>

In [3]:
import numpy

arr = numpy.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>

In [4]:
import numpy as np #np is an alias name for numpy

arr = np.array(list)
print(arr)
print(type(arr))

In [6]:
# array ndmin 

import numpy as np

arr = np.array([3, 5, 6, 'hello'])
print(arr)
print(arr.dtype)
print(type(arr))

['3' '5' '6' 'hello']
<U21
<class 'numpy.ndarray'>


In [13]:
arr = np.array({'a': 10, 'b': 20})
print(arr)
print(arr.dtype)
print(type(arr))

{'a': 10, 'b': 20}
object
<class 'numpy.ndarray'>


In [15]:
# ndarray operations 

arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# sum
out = np.max(arr, axis=0)
print(out)

[ 9 10 11 12]


In [39]:
a = np.array([-3.5, 2.23, 1.009])

out = np.floor(a)
print(out)

[-4.  2.  1.]


In [48]:
print(np.empty((2, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
