In [8]:
# Task 1 Solution
import numpy as np
inp = list(map(eval, input().split()))
arr = np.array(inp, dtype=float)
print(arr)
print(np.flip(arr))


[ 1.   3.   4.  -5.   0.5]
[ 0.5 -5.   4.   3.   1. ]


In [10]:
#task 2 sol
inp = list(map(eval, input().split()))
arr = np.array(inp)
# arr = arr.reshape(3,3)
arr.shape = 3, 3
print(arr)

[[4 5 6]
 [7 7 8]
 [2 3 4]]


In [11]:
# task 3 Solution 
n,m=list(map(int,input().split()))
print(np.eye(n,m))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# task 4 Solution 
import numpy as np
N, M = list(map(eval, input().split()))
arr1 = []
for _ in range(N):
    arr1.append(list(map(eval, input().split())))
arr2 = []
for _ in range(N):
    arr2.append(list(map(eval, input().split())))

arr1 = np.array(arr1)
arr2 = np.array(arr2)

print(np.add(arr1, arr2))


In [1]:
# task 1
import numpy as np
lst = list(map(eval, input().split()))

arr = np.array(lst, dtype=float)

# print(arr)
print(np.flip(arr))

[ 3.  5.  8.  2. -4.]
[-4.  2.  8.  5.  3.]


In [2]:
# task 2
import numpy as np
lst = list(map(eval, input().split()))

arr = np.array(lst).reshape((3, 3))
print(arr)

[[3 4 6]
 [2 3 4]
 [5 6 8]]
