In [3]:
# arr[dim1:dimn, element1:element4]

# 1-d array 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Extract a slice from index 1 to 3 (exclusive)
slice_ = arr[1:3]
# slice_ = arr[1,2]
print(slice_)  # Output: [2 3]


[2 3]


In [6]:
# matrix (multi-dimensional)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extract a slice from rows 0 to 1 and columns 1 to 2
slice_2d = arr_2d[0:2, 1:3]
print(slice_2d)
# Output:
# [[2 3]
#  [5 6]]


[[2 3]
 [5 6]]


In [13]:
# Advanced slicing: You can use slices, integers, ellipsis (...), or np.newaxis to create more complex slices.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Using ellipsis to skip certain dimensions
# slice_2d = arr_2d[..., 1:3]
slice_2d = arr_2d[:,1:3]
print(slice_2d)
# Output: [2 5 8]




[[2 3]
 [5 6]
 [8 9]]


In [14]:
# Using integer array indexing to select specific elements
indexes = np.array([0, 2])
slice_2d = arr_2d[:, indexes]
print(slice_2d)
# Output:
# [[1 3]
#  [4 6]
#  [7 9]]

# Using np.newaxis to increase the dimensionality of the result


[[1 3]
 [4 6]
 [7 9]]


In [15]:
slice_2d = arr_2d[:, np.newaxis, :]
print(slice_2d)  # Output: (3, 1, 3)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [2]:
import numpy as np
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
slice_3d = arr_3d[::-1, ::-1, ::-1]
print(slice_3d)

[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


In [3]:
arr = np.array([[1, 3, 5], 
                [4, 7, 9],
                [1, 4, 0]])


In [12]:
print(arr[:, 2])

[[1 5]
 [4 9]
 [1 0]]


In [34]:
import numpy as np
arr = np.array([3, 5, 7, 9])
out = arr[:]
print(arr)

[3 5 7 9]


In [35]:
arr2d = np.array([[2, 4],
                 [1, 6],
                  [1, 0]])


In [38]:
x = arr2d[..., 1]
print(x)

[4 6 0]


In [33]:
ar = np.zeros((2, 2, 3, 4))
print(ar)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [41]:
lst = [1, 2, 3, 4, 5, 10]

print(lst[-1:])

[10]


In [ ]:
ls