In \[ \]:

    # NumPy Creating Arrays
    # NumPy Array Indexing
    # NumPy Array Slicing

In \[1\]:

    pip install numpy

    Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (1.18.1)
    Note: you may need to restart the kernel to use updated packages.

In \[30\]:

    import numpy
    print(numpy.__version__)

    1.18.1

In \[32\]:

    list = [1,2,3,4,5,6]
    print(type(list))

    <class 'list'>

In \[33\]:

    import numpy

    arr = numpy.array(list)
    print(arr)
    print(type(arr))

    [1 2 3 4 5 6]
    <class 'numpy.ndarray'>

In \[34\]:

    import numpy as np #np is an alias name for numpy

    arr = np.array(list)
    print(arr)
    print(type(arr))

    [1 2 3 4 5 6]
    <class 'numpy.ndarray'>

In \[7\]:

    #version
    print(np.__version__)

    1.18.1

In \[8\]:

    # Create a NumPy ndarray Object
    # The array object in NumPy is called ndarray.

    arr = np.array([1, 2, 3, 4, 5])

    print(arr)
    print(type(arr))

    [1 2 3 4 5]
    <class 'numpy.ndarray'>

In \[36\]:

    obj = (1, 2, 3, 4, 5)
    print(type(obj))
    print(obj)
    arr = np.array(obj)
    print(arr)
    print(type(arr))

    <class 'tuple'>
    (1, 2, 3, 4, 5)
    [1 2 3 4 5]
    <class 'numpy.ndarray'>

In \[175\]:

    obj = {"CA": 8, "CB": 10}
    print(type(obj))

    arr = np.array(obj)
    print(arr)
    print(type(arr))

    <class 'dict'>
    {'CA': 8, 'CB': 10}
    <class 'numpy.ndarray'>

In \[43\]:

    numlist = [  [ [5,6,7],[4,3,6,8] ] , [[5,6,7]], [[5,6,7],[4,3],[6,8]] ]
    print(len(numlist))
    print(len(numlist[0]))
    print(len(numlist[1]))
    print(len(numlist[2]))
    print(len(numlist[2][1]))

    3
    2
    1
    3
    2

In \[50\]:

    arr = np.array(["Rohan", "Riya"])
    print(arr)
    print(type(arr))
    print(arr.ndim)
    print("============")
    arr = np.array(67)
    print(arr)
    print(type(arr))
    print(arr.ndim)

    ['Rohan' 'Riya']
    <class 'numpy.ndarray'>
    1
    ============
    67
    <class 'numpy.ndarray'>
    0

In \[181\]:

    # Dimensions in Arrays
    # A dimension in arrays is one level of array depth (nested arrays)
    aarr = np.array(23)
    print(aarr)
    print("Dimension of aarr = ",aarr.ndim)

    23
    Dimension of aarr =  0

In \[183\]:

    aaarr = np.array([1, 2, 3,4, 5, 6])

    print(aaarr)
    print("Dimension of aaarr = ",aaarr.ndim)

    [1 2 3 4 5 6]
    Dimension of aaarr =  1

In \[15\]:

    barr = np.array([[1, 2, 3], [4, 5, 6]])

    print(barr)
    print("Dimension of barr = ",barr.ndim)

    [[1 2 3]
     [4 5 6]]
    Dimension of barr =  2

In \[4\]:

    list = [1,2,"Rahul"]
    print(list)

    [1, 2, 'Rahul']

In \[16\]:

    import numpy as np
    arr = np.array(456)
    print(arr)
    print(type(arr))
    print(arr.ndim)

    456
    <class 'numpy.ndarray'>
    0

In \[6\]:

    import numpy as np
    carr = np.array([
                   [ [1,2] ],
                   [ [1,2,9] ] , 
                   [ [1,2] ]
                ])

    print(carr)
    print("Dimension of carr = ",carr.ndim)
    print(carr.shape)

    [[list([1, 2])]
     [list([1, 2, 9])]
     [list([1, 2])]]
    Dimension of carr =  2
    (3, 1)

In \[34\]:

    var = (a*a for a in range(8))
    print(var)
    numlist = list(var)
    print(type(numlist))
    print(numlist)

    <generator object <genexpr> at 0x000001C90E4A6B48>
    <class 'list'>
    [0, 1, 4, 9, 16, 25, 36, 49]

In \[19\]:

    import numpy as np
    carr1 = np.array([
                   [ [1,2,3],[4,5,6],[7,8,9] ],
                   [ [1,2,3],[4,5,6],[7,8,9] ],
                   [ [1,2,3],[4,5,6],[7,8,9] ],
                ])

    print(carr1[0][1][2]) #1st 2-D, 2nd row, 3rd element
    print(carr1[0,1,2])
    print(carr1)
    print("Dimension of carr1 = ",carr1.ndim)
    print(carr1.shape)

    6
    6
    [[[1 2 3]
      [4 5 6]
      [7 8 9]]

     [[1 2 3]
      [4 5 6]
      [7 8 9]]

     [[1 2 3]
      [4 5 6]
      [7 8 9]]]
    Dimension of carr1 =  3
    (3, 3, 3)

In \[143\]:

    print(aarr.ndim)
    print(barr.ndim)
    print(carr.ndim)

    0
    2
    3

In \[24\]:

    narr = np.array([1, 2, 3, 4], ndmin=5)
     
    print(narr)
    print('number of dimensions :', narr.ndim)

    print(narr[0]) # 4-d
    print(narr[0,0]) # 3-d
    print(narr[0,0,0]) # 2-d
    print(narr[0,0,0,0]) # 1-d
    print(narr[0,0,0,0,1]) #2nd element from above 1-d array

    [[[[[1 2 3 4]]]]]
    number of dimensions : 5
    [[[[1 2 3 4]]]]
    [[[1 2 3 4]]]
    [[1 2 3 4]]
    [1 2 3 4]
    2

In \[30\]:

    # Higher Dimensional Arrays
    narr = np.array([1, 2, 3, 4], ndmin=5)
    print(narr)
    print(narr[0])
    print('number of dimensions :', narr.ndim)
    print(narr[0,0,0])

    [[[[[1 2 3 4]]]]]
    [[[[1 2 3 4]]]]
    number of dimensions : 5
    [[1 2 3 4]]

In \[36\]:

    # NumPy Array Indexing
    # Access Array Elements
    print(barr, end = "\n\n")
    print(barr[0])

    [[1 2 3]
     [4 5 6]]

    [1 2 3]

In \[39\]:

    # Access 2-D Arrays
    print('2nd element on 2nd row: ',barr[1,1])

    2nd element on 2nd row:  5

In \[42\]:

    # Access 3-D Arrays
    darr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
    print("Dimenson of the array: ",darr.ndim)
    print('3rd element on 2nd row in first 2D Array: ',arr[0, 1, 2])

    Dimenson of the array:  3
    3rd element on 2nd row in first 2D Array:  6

In \[18\]:

    # Negative Indexing
    arr = np.array([
                    [1,2,3,4,5], 
                    [6,7,8,9,10]
                  ])

    print('2nd Last element from 2nd dim: ', arr[1, -2])
    print('2nd Last element from 2nd dim: ', arr[-1, -2])

    print('2nd Last element from 1st dim: ', arr[0, -2])
    print('2nd Last element from 1st dim: ', arr[-2, -2])

    2nd Last element from 2nd dim:  9
    2nd Last element from 2nd dim:  9
    2nd Last element from 1st dim:  4
    2nd Last element from 1st dim:  4

In \[36\]:

    # NumPy Array Slicing
    # taking elements from one given index to another given index.
    # [start:end] or [start:end:step].
    arr = np.array([15, 32, 23, 24, 55,76, 87])

    print(arr)
    print(arr[0:len(arr):1])

    print(arr[1:5])
    print(arr[1:5:1])

    print(arr[1:5:2])

    print(arr[:5])
    print(arr[1:])
    print(arr[::2])
    print(arr[1::2])

    [15 32 23 24 55 76 87]
    [15 32 23 24 55 76 87]
    [32 23 24 55]
    [32 23 24 55]
    [32 24]
    [15 32 23 24 55]
    [32 23 24 55 76 87]
    [15 23 55 87]
    [32 24 76]

In \[37\]:

    # Negative Slicing
    print(arr)
    print(arr[-3:-1])

    [15 32 23 24 55 76 87]
    [55 76]

In \[22\]:

    # Step
    print(arr[1:5:2])
    print(arr[::2])

    [32 24]
    [15 23 55 87]

In \[39\]:

    # Slicing 2-D Arrays
    arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    # [dim1:dim2, elementindex1: elementindex2]
    print(arr[0, 1:4], end = "\n\n")

    print(arr[0:2, 3], end = "\n\n")

    print(arr[0:2, 1:4:2], end = "\n\n")

    [2 3 4]

    [4 9]

    [[2 4]
     [7 9]]

In \[ \]:

    # NumPy Data Types

In \[ \]:

    # NumPy Copy vs View
    # NumPy Array Shape
    # NumPy Array Reshape

In \[33\]:

    # NumPy Copy vs View
    #copy()
    arr = np.array([1, 2, 3, 4, 5])
    arrcopy = arr.copy()
    arr[0] = 42

    print(arr)
    print(arrcopy)

    [42  2  3  4  5]
    [1 2 3 4 5]

In \[34\]:

    # NumPy Copy vs View
    #view()
    arr = np.array([1, 2, 3, 4, 5])
    arrview = arr.view()
    arr[0] = 42

    print(arr)
    print(arrview)

    [42  2  3  4  5]
    [42  2  3  4  5]

In \[35\]:

    # NumPy Copy vs View
    #view()
    arr = np.array([1, 2, 3, 4, 5])
    arrview = arr.view()
    arrview[0] = 44

    print(arr)
    print(arrview)

    [44  2  3  4  5]
    [44  2  3  4  5]

In \[38\]:

    c = arr.copy()
    v = arr.view()

    print(c.base)
    print(v.base)

    None
    [44  2  3  4  5]

In \[45\]:

    # NumPy Array Shape
    # number of elements in each dimension
    print(arr)
    print(arr.shape)

    print("===========")
    print(barr)
    print(barr.shape)

    print("===========")
    print(narr)
    print(narr.shape)

    [44  2  3  4  5]
    (5,)
    ===========
    [[1 2 3]
     [4 5 6]]
    (2, 3)
    ===========
    [[[[[1 2 3 4]]]]]
    (1, 1, 1, 1, 4)

In \[46\]:

    # NumPy Array Reshaping
    # Reshape From 1-D to 2-D
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    newarr = arr.reshape(5, 2)
    print(newarr)

    [[ 1  2]
     [ 3  4]
     [ 5  6]
     [ 7  8]
     [ 9 10]]

In \[47\]:

    newarr = arr.reshape(2, 5)
    print(newarr)

    [[ 1  2  3  4  5]
     [ 6  7  8  9 10]]

In \[53\]:

    # 1-D to 3-D
    newarr = arr.reshape(2,1,5)
    print(newarr)

    [[[ 1  2  3  4  5]]

     [[ 6  7  8  9 10]]]

In \[54\]:

    print(newarr.base)

    [ 1  2  3  4  5  6  7  8  9 10]

In \[58\]:

    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

    newarr = arr.reshape(2, 2, -1)

    print(newarr)

    [[[ 1  2  3]
      [ 4  5  6]]

     [[ 7  8  9]
      [10 11 12]]]

In \[60\]:

    newarr = arr.reshape(2, -1)

    print(newarr)

    [[ 1  2  3  4  5  6]
     [ 7  8  9 10 11 12]]

In \[ \]:

    # NumPy Array Iterating
    # NumPy Array Join
    # NumPy Array Split

In \[92\]:

    # NumPy Array Iterating
    arr2d = np.array([[1, 2, 3], [4, 5, 6]])

    arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In \[93\]:

    # NumPy Array Join
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])

    arr = np.concatenate((arr1, arr2))
    print(arr)

    [1 2 3 4 5 6]

In \[94\]:

    # stacking is done along a new axis
    arr = np.stack((arr1, arr2), axis=1)

    print(arr)
    print(arr.ndim)

    [[1 4]
     [2 5]
     [3 6]]
    2

In \[95\]:

    arr1 = np.array([[1, 2], [3, 4]])

    arr2 = np.array([[5, 6], [7, 8]])

    arr = np.concatenate((arr1, arr2), axis=1)

    print(arr)

    [[1 2 5 6]
     [3 4 7 8]]

In \[84\]:

    # stacking is done along a new axis
    arr = np.stack((arr1, arr2), axis=1)

    print(arr)
    print(arr.ndim)

    [[[1 2]
      [5 6]]

     [[3 4]
      [7 8]]]
    3

In \[96\]:

    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])

    arr = np.hstack((arr1, arr2))
    print(arr, end = "\n\n")

    arr = np.vstack((arr1, arr2))
    print(arr, end = "\n\n")

    arr = np.dstack((arr1, arr2))
    print(arr, end = "\n\n")

    [1 2 3 4 5 6]

    [[1 2 3]
     [4 5 6]]

    [[[1 4]
      [2 5]
      [3 6]]]

In \[107\]:

    # Splitting NumPy Arrays
    arr = np.array([1, 2, 3, 4, 5, 6])

    newarr = np.array_split(arr, 3)

    print(newarr)
    for eacharr in newarr:
        print(eacharr)

    [array([1, 2]), array([3, 4]), array([5, 6])]
    [1 2]
    [3 4]
    [5 6]

In \[40\]:

    arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

    newarr = np.array_split(arr, 3)

    print(newarr)
    for eacharr in newarr:
        print(eacharr)

    [array([[1, 2],
           [3, 4]]), array([[5, 6],
           [7, 8]]), array([[ 9, 10],
           [11, 12]])]
    [[1 2]
     [3 4]]
    [[5 6]
     [7 8]]
    [[ 9 10]
     [11 12]]

In \[44\]:

    newarr = np.array_split(arr, 3, axis=1)

    print(newarr)
    for eacharr in newarr:
        print(eacharr)

    [array([[ 1],
           [ 3],
           [ 5],
           [ 7],
           [ 9],
           [11]]), array([[ 2],
           [ 4],
           [ 6],
           [ 8],
           [10],
           [12]]), array([], shape=(6, 0), dtype=int32)]
    [[ 1]
     [ 3]
     [ 5]
     [ 7]
     [ 9]
     [11]]
    [[ 2]
     [ 4]
     [ 6]
     [ 8]
     [10]
     [12]]
    []

In \[ \]:

    # NumPy Array Search
    # NumPy Array Sort
    # NumPy Array Filter

In \[51\]:

    # NumPy Array Search
    import numpy as np

    arr = np.array([11, 2, 3, 14, 15, 16, 4])
    x = np.where(arr == 4)
    print(x)
    x = np.where(arr>10)
    print(x)

    (array([6], dtype=int64),)
    (array([0, 3, 4, 5], dtype=int64),)

In \[53\]:

    # NumPy Array Sort
    # Search Sorted
    # There is a method called searchsorted() which performs a binary search 
    # in the array, and returns the index where the specified value would be 
    # inserted to maintain the search order.

    arr = np.array([6, 7, 8, 9])
    x = np.searchsorted(arr, 9)
    print(x)

    3

In \[54\]:

    arr = np.array([6, 7, 8, 9])
    x = np.searchsorted(arr, 7, side='right')
    print(x)

    2

In \[56\]:

    arr = np.array([1, 3, 5, 7])
    x = np.searchsorted(arr, [2, 4, 9])
    print(x)

    [1 2 4]

In \[57\]:

    #Sort Array
    arr = np.array([[3, 2, 4], [5, 0, 1]])
    print(np.sort(arr))

    [[2 3 4]
     [0 1 5]]

In \[ \]:

    # NumPy Array Filter
    # Get some elements from an existing array and create a new array out 
    # of them is called filtering.

    # In NumPy, you filter an array using a boolean index list.

In \[58\]:

    arr = np.array([41, 42, 43, 44])

    x = [True, False, True, False]

    newarr = arr[x]

    print(newarr)

    [41 43]

In \[59\]:

    arr = np.array([101,102,103,104])

    filter_arr = []

    for element in arr:
        if element%2 == 0:
            filter_arr.append(True)
        else:
            filter_arr.append(False)

    newarr = arr[filter_arr]

    print(filter_arr)
    print(newarr)

    [False, True, False, True]
    [102 104]

In \[63\]:

    arr = np.array([101,102,103,104])

    filter_arr = arr%3 == 0
    print(filter_arr)

    newarr = arr[filter_arr]
    print(newarr)

    [False  True False False]
    [102]

In \[118\]:

    import numpy as np
    import time

    # Creating a large list
    size = 1000000
    my_list = list(range(size))

    # Creating a NumPy array from the list
    my_array = np.array(my_list)

    # Adding elements of list
    start_time = time.time()
    sum_list = sum(my_list)
    list_time = time.time() - start_time

    # Adding elements of NumPy array
    start_time = time.time()
    sum_array = np.sum(my_array)
    array_time = time.time() - start_time

    print("Time taken to sum elements of list:", list_time)
    print("Time taken to sum elements of NumPy array:", array_time)

    speed_up = list_time / array_time
    print("NumPy is approximately", speed_up, "times faster than lists for this operation.")

    Time taken to sum elements of list: 0.06881523132324219
    Time taken to sum elements of NumPy array: 0.0019953250885009766
    NumPy is approximately 34.488230373999286 times faster than lists for this operation.

In \[ \]:

     

In \[ \]: